[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  REACT_APP_API_URL = "https://daily-shipment-tracker.onrender.com"
  REACT_APP_SOCKET_URL = "https://daily-shipment-tracker.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 