services:
  - type: web
    name: daily-shipment-tracker
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && chmod +x render-start.sh
    startCommand: cd backend && bash render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://asafasaf5347:asafasaf5347@cluster0.lyz67.mongodb.net/shipment-tracker?retryWrites=true&w=majority&appName=Cluster0 