services:
  - type: web
    name: daily-shipment-tracker
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    nodeVersion: 18.19.1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://daily_admin:1ArUfF8oH5N97Ggy@ops.hm6y7nw.mongodb.net/daily?retryWrites=true&w=majority&appName=OPS
      - key: JWT_SECRET
        value: mysecrettoken-production-7d6f8a9b5c4e3d2f1a0b9c8d7e6f5a4b
      - key: CORS_ORIGINS
        value: https://veleka-shipments-daily-report.netlify.app,https://daily-shipments.netlify.app,https://daily-tracking.netlify.app,https://daily-admin.netlify.app
      - key: ALLOWED_ORIGINS
        value: https://veleka-shipments-daily-report.netlify.app,https://daily-shipments.netlify.app,https://daily-tracking.netlify.app,https://daily-admin.netlify.app
      - key: DD_API_KEY
        sync: false
      - key: DD_SITE
        value: "datadoghq.com"
      - key: DD_ENV
        value: "production"
      - key: DD_SERVICE
        value: "daily-shipment-tracker"
      - key: DD_LOGS_INJECTION
        value: "true"
      - key: DD_TRACE_ENABLED
        value: "true"
      - key: DD_PROFILING_ENABLED
        value: "true"
      - key: DD_APM_ENABLED
        value: "true"
      - key: DD_VERSION
        value: "1.0.0"
    buildFilter:
      paths:
        - server.js
        - package.json
        - package-lock.json
        - routes/
        - models/
        - middleware/
        - config/
        - utils/ 