services:
  - type: web
    name: daily-shipment-tracker
    env: node
    region: oregon
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node src/server.js
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://daily_admin:1ArUfF8oH5N97Ggy@ops.hm6y7nw.mongodb.net/daily?retryWrites=true&w=majority&appName=OPS
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 7d
      - key: ALLOWED_ORIGINS
        value: https://daily-shipment-tracker.onrender.com,https://veleka-shipments-daily-report.netlify.app,https://daily-shipments.netlify.app,https://daily-tracking.netlify.app,https://daily-admin.netlify.app
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://veleka-shipments-daily-report.netlify.app,https://daily-shipments.netlify.app,https://daily-tracking.netlify.app,https://daily-admin.netlify.app
      - key: DD_API_KEY
        sync: false
      - key: DD_SITE
        value: "datadoghq.com"
      - key: DD_ENV
        value: "production"
      - key: DD_SERVICE
        value: "daily-shipment-tracker"
      - key: DD_LOGS_INJECTION
        value: "true"
      - key: DD_TRACE_ENABLED
        value: "true"
      - key: DD_PROFILING_ENABLED
        value: "true"
      - key: DD_APM_ENABLED
        value: "true"
      - key: DD_VERSION
        value: "1.0.0"
    buildFilter:
      paths:
        - src/**/*
        - package.json
        - package-lock.json
        - index.js
        - server.js
        - dns-resolution-debug.js
        - routes/
        - models/
        - middleware/
        - config/
        - utils/ 