services:
  - type: web
    name: daily-shipment-tracker
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && chmod +x render-start.sh
    startCommand: cd backend && bash render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://daily_admin:1ArUfF8oH5N97Ggy@ops.hm6y7nw.mongodb.net/daily?retryWrites=true&w=majority&appName=OPS 