services:
  - type: web
    name: daily-shipment-tracker
    env: node
    region: oregon
    buildCommand: npm install && cd frontend && npm install && npm run build && cd ..
    startCommand: node backend/src/server.js
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://daily-shipment-tracker.onrender.com
      - key: ALLOWED_ORIGINS
        value: https://daily-shipment-tracker.onrender.com,https://veleka-shipments-daily-report.netlify.app,https://daily-shipments.netlify.app,https://daily-tracking.netlify.app,https://daily-admin.netlify.app
      - key: CORS_ORIGINS
        value: https://veleka-shipments-daily-report.netlify.app,https://daily-shipments.netlify.app,https://daily-tracking.netlify.app,https://daily-admin.netlify.app
      - key: DD_API_KEY
        sync: false
      - key: DD_SITE
        value: "datadoghq.com"
      - key: DD_ENV
        value: "production"
      - key: DD_SERVICE
        value: "daily-shipment-tracker"
      - key: DD_LOGS_INJECTION
        value: "true"
      - key: DD_TRACE_ENABLED
        value: "true"
      - key: DD_PROFILING_ENABLED
        value: "true"
      - key: DD_APM_ENABLED
        value: "true"
      - key: DD_VERSION
        value: "1.0.0"
    buildFilter:
      paths:
        - src/**/*
        - package.json
        - package-lock.json
        - index.js
        - server.js
        - dns-resolution-debug.js
        - routes/
        - models/
        - middleware/
        - config/
        - utils/
    healthCheckPath: /health 