services:
  - type: web
    name: daily-shipment-tracker
    runtime: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: chmod +x render-start-debug.sh && ./render-start-debug.sh
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    buildFilter:
      paths:
        - src/server.js
        - src/index.js
        - src/routes/**
        - package.json
        - package-lock.json
        - dns-resolution-debug.js
        - server.js
        - index.js
        - render-build.sh
        - render-start-debug.sh 