services:
  - type: web
    name: daily-shipment-tracker
    runtime: node
    buildCommand: npm install
    startCommand: node -r ./dns-resolution-debug.js src/server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    buildFilter:
      paths:
        - src/server.js
        - package.json
        - package-lock.json
        - index.js
        - dns-resolution-debug.js
        - render-start.sh
        - connection-test.js 