services:
  - type: web
    name: daily-shipment-tracker
    runtime: node
    buildCommand: npm install
    startCommand: bash render-start.sh
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    buildFilter:
      paths:
        - src/server.js
        - src/index.js
        - package.json
        - package-lock.json
        - dns-resolution-debug.js
        - render-start.sh
        - connection-test.js 