// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Shipment
export const GET_SHIPMENTS = 'GET_SHIPMENTS';
export const GET_SHIPMENT = 'GET_SHIPMENT';
export const SHIPMENT_ERROR = 'SHIPMENT_ERROR';
export const ADD_SHIPMENT = 'ADD_SHIPMENT';
export const UPDATE_SHIPMENT = 'UPDATE_SHIPMENT';
export const DELETE_SHIPMENT = 'DELETE_SHIPMENT';
export const CLEAR_SHIPMENT = 'CLEAR_SHIPMENT';
export const SHIPMENT_LOADING = 'SHIPMENT_LOADING';

// Dashboard
export const GET_DASHBOARD_SUMMARY = 'GET_DASHBOARD_SUMMARY';
export const GET_SHIPMENTS_BY_CUSTOMER = 'GET_SHIPMENTS_BY_CUSTOMER';
export const GET_SHIPMENTS_BY_DATE = 'GET_SHIPMENTS_BY_DATE';
export const GET_OVERDUE_NON_INVOICED = 'GET_OVERDUE_NON_INVOICED';
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';
export const DASHBOARD_LOADING = 'DASHBOARD_LOADING'; 